version: 2.1
# Use a package of configuration called an orb.
orbs:
  node: circleci/node@1.1.6

jobs:  
  build-and-test:
    working_directory: ~/angular-circle-surge
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: angular-circle-surge-{{ .Branch }}--{{ checksum "package-lock.json"}}
      - run: npm install
      - save_cache:
          key: angular-circleci-surge- {{ .Branch }}--{{ checksum "package-lock.json"}}
          paths: 
           - "node_modules"
      - run: npm run test -- --no-watch --no-progress --browser=ChromeHeadlessCI      
# Orchestrate or schedule a set of jobs
workflows:
   build-and-test:
     jobs:
       - build-and-test
